CREATE TABLE users (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE files (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    gradelvl VARCHAR(50) NOT NULL UNIQUE,
    subjec_t VARCHAR(50) NOT NULL UNIQUE,
    quarter_no VARCHAR(50) NOT NULL UNIQUE,
    module_no VARCHAR(50) NOT NULL UNIQUE,
    title VARCHAR(50) NOT NULL UNIQUE,
    size INT
);